wifi ssid problem solved

diff --git a/scripts/wifi-ssid b/scripts/wifi-ssid
--- a/scripts/wifi-ssid
+++ b/scripts/wifi-ssid
@@ -2,3 +2,12 @@
 
 # Extract the wifi username (SSID)
 # Refer: "iw dev wlan0 link" command output for this
+
+ssid=$(iw dev wlan0 link | grep "ssid" | awk '{print $2}')
+
+if [[ -z "$ssid" ]]; then
+  echo "Could not find SSID"
+  exit 1
+fi
+
+echo "Your WiFi username (SSID): $ssid"
